### ISSUE TITLE
width and left properties for transition?

### ISSUE THREAD

**Issue by MaKleSoft** [Polymer/paper-tabs#57]
From https://github.com/Polymer/paper-tabs/blob/master/paper-tabs.css#L59:

```css
transition: width, left;
```

I thought it was common knowledge by now that animating width/height and position properties is slow? For example, see: http://www.paulirish.com/2012/why-moving-elements-with-translate-is-better-than-posabs-topleft/

**Comment by frankiefu** [comment]
There is a 0.8-preview version that uses transform.
https://github.com/Polymer/paper-tabs/blob/0.8-preview/paper-tabs.html#L136

**Comment by MaKleSoft** [comment]
Awesome! Great to see that you guys are working on performance.
