### ISSUE TITLE
noSlide, noBar not working?

### ISSUE THREAD

**Issue by adaliszk** [Polymer/paper-tabs#72]
It's a newbie question, on the paper-taps documentation page (https://elements.polymer-project.org/elements/paper-tabs) I saw the possibility that the bottom bar can be disabled, I saw the "selected" also in the api reference so I assumed that every item in there can be accessed as a html property, but it did not work for me :/ Can somebody help me with it?

```
<paper-tabs selected="0" noink="true" noSlide="true" noBar="true">
    <paper-tab ontap="Application.switchTab(0);> Tab#0 </paper-tab>
    <paper-tab ontap="Application.switchTab(1);> Tab#1 </paper-tab>
    <paper-tab ontap="Application.switchTab(2);> Tab#2 </paper-tab>
    <paper-tab ontap="Application.switchTab(3);> Tab#3 </paper-tab>
</paper-tabs>
```

**Comment by notwaldorf** [comment]
In html, the attributes are dash cased, not camel cases. So it should be `no-slide` and `no-bar` instead. :)

**Comment by adaliszk** [comment]
@notwaldorf Thanks thats working! Can you add least a notice on the documentation page with this tip on every API Reference Properties for newbies? Just a tooltip should be enough with a link to the guide, what I founded after your answer :) (https://elements.polymer-project.org/guides/using-elements#polymer-element-apis) Littlebit confusing that the doc say "Properties" and not working because this conversion. Okay I should readed the guide but I readed until "Using elements" section and after it worked so I closed and not needed any property without example for two weeks.
